// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL?.trim()) {
  throw new Error(
    'Missing required environment variable: VITE_SUPABASE_URL. Set it in your .env.local (or deployment environment) before starting the app.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY?.trim()) {
  throw new Error(
    'Missing required environment variable: VITE_SUPABASE_PUBLISHABLE_KEY. Set it in your .env.local (or deployment environment) before starting the app.'
  );
}

try {
  new URL(SUPABASE_URL);
} catch {
  throw new Error(
    `Invalid VITE_SUPABASE_URL value: "${SUPABASE_URL}". Expected a valid absolute URL such as https://<project-ref>.supabase.co`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
